name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      run: dotnet build -c Release /p:Version=${{ github.event.release.tag_name }}
      
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
      
    - name: Package
      run: dotnet publish -c Release /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/halamah/aspnetcorekafka"
      
    - name: Archive Core
      uses: actions/upload-artifact@v1
      with:
        name: AspNetCore.Kafka
        path: ./Core/bin/Release/AspNetCore.Kafka.${{ github.event.release.tag_name }}.nupkg
        
    - name: Archive Mock
      uses: actions/upload-artifact@v1
      with:
        name: AspNetCore.Kafka.Mock
        path: ./Mock/bin/Release/AspNetCore.Kafka.Mock.${{ github.event.release.tag_name }}.nupkg
        
    - name: Setup Nuget sources
      run: dotnet nuget add source --name github "https://nuget.pkg.github.com/halamah/index.json"
      
    - name: Publish to GitHub
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate --no-symbols

    - name: Publish to Nuget
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.nuget_api_key }} --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
